import Head from "next/head"

export default function Home () {
  return (
    <div className='flex items-center justify-center min-h-screen'>
      <Head>
        <title>Bread</title>
        <meta name='description' content='Generated by create next app' />
        <link
          rel='icon'
          href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>🍞</text></svg>"
        />
      </Head>
      <p>Test</p>
    </div>
  )
}
