import Head from "next/head"
import CodeRun from "../components/CodeRun-proj"

export default function Home () {
  return (
    <div className='flex flex-col w-screen h-screen'>
      <Head>
        <title>Bread</title>
        <meta name='description' content='Generated by create next app' />
        <link
          rel='icon'
          href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>🍞</text></svg>"
        />
      </Head>
      <div className='flex items-center justify-start w-screen h-12 bg-slate-900'>
        <span className='pl-5 font-sans font-medium text-white'>🧋 malloctime</span>
      </div>
      <div className='grid h-screen grid-cols-2'>
        <div className='bg-slate-800'></div>
        <CodeRun />
      </div>
      <div className='h-12 bg-slate-900 w-inherit'></div>
    </div>
  )
}
